buildNumber: unknown
buildTime: unknown
gitRevision: unknown
gitBranch: unknown

spring:
  datasource:
    url: jdbc:mysql://localhost:13308/ecommerce_inventory_mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: rabbitmq-user
    password: rabbitmq-password
    publisher-confirms: true
